### 
GET http://localhost:3001/api/blogs

###

# GET a blog by id
  http://localhost:3001/api/blogs/1

###

# POST a new blog
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "author": "Anjana Leo",
    "url": "https://www.myexample.com",
    "title": "Test Blog2"
}

